### ISSUE TITLE
Issue trying to setup python interface

### ISSUE THREAD

**Issue by harpaf13** [atomisticnet/aenet#14]
After compiling aenet successfully, I followed the instructions in the README.rst in the python3/ folder to install aenet-predict.py and aenet-md.py.  I used the following commands:

$ cd ../src
$ make -f ./makefiles/Makefile.XXX lib
$ cd -
$ python setup.py build_ext --inplace

and when I try and run `aenet-md.py` I get the following error which looks like something has gone wrong in using cython for the ANNPotentials class:

```
Traceback (most recent call last):
  File "/u/fs1/afh41/.conda/envs/ml-tools/bin/aenet-predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('aenet==0.1.0a1', 'aenet-predict.py')
  File "/u/fs1/afh41/.conda/envs/ml-tools/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/u/fs1/afh41/.conda/envs/ml-tools/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/home/users/afh41/.local/lib/python3.7/site-packages/aenet-0.1.0a1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/aenet-predict.py", line 40, in <module>
    from aenet.ase_calculator import ANNCalculator
  File "/u/fs1/afh41/.local/lib/python3.7/site-packages/aenet-0.1.0a1-py3.7-linux-x86_64.egg/aenet/ase_calculator.py", line 24, in <module>
    from aenet.core import ANNPotentials
ImportError: /u/fs1/afh41/.local/lib/python3.7/site-packages/aenet-0.1.0a1-py3.7-linux-x86_64.egg/aenet/core.cpython-37m-x86_64-linux-gnu.so: undefined symbol: mpi_comm_rank_
```

**Comment by nartrith** [comment]
@harpaf13 I don't know if your issue has been resolved by now. But in case somebody else encounters this problem, here a late response:

Based on the error message alone, it is unclear what exactly went wrong. It could be that the `aenet` library was built with a different compiler from the one used by Cython. Cython uses most likely the GNU compiler collection, so I would recommend trying to built the library with the GNU Fortran compiler as well (note that this might be different on Mac OS).

**Comment by nartrith** [comment]
Closing because of a lack of information.
